"""empty message

Revision ID: 314de9b8143c
Revises: 4c3cec0984ec
Create Date: 2023-04-10 13:33:34.566514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '314de9b8143c'
down_revision = '4c3cec0984ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('social_id', sa.Text(), nullable=True),
    sa.Column('social_type', sa.Text(), nullable=True),
    sa.Column('activated', sa.BOOLEAN(), server_default='false', nullable=False),
    sa.Column('_password', sa.Text(), nullable=True),
    sa.Column('fullname', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('picture', sa.Text(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('social_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
