"""empty message

Revision ID: 4c3cec0984ec
Revises: 917463906108
Create Date: 2023-04-10 13:31:58.149358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c3cec0984ec'
down_revision = '917463906108'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('social_id', sa.Text(), nullable=True),
    sa.Column('social_type', sa.Text(), nullable=True),
    sa.Column('activated', sa.BOOLEAN(), server_default='f', nullable=False),
    sa.Column('_password', sa.Text(), nullable=True),
    sa.Column('fullname', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('picture', sa.Text(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('social_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
