"""empty message

Revision ID: 71267147391a
Revises: 595d2e35db4c
Create Date: 2023-04-11 18:47:58.268144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71267147391a'
down_revision = '595d2e35db4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
