"""empty message

Revision ID: 917463906108
Revises: da160e04c290
Create Date: 2023-04-10 13:30:15.102082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '917463906108'
down_revision = 'da160e04c290'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('social_id', sa.String(), nullable=True),
    sa.Column('social_type', sa.String(), nullable=True),
    sa.Column('activated', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('_password', sa.String(), nullable=True),
    sa.Column('fullname', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('picture', sa.String(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('social_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
